//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimeTime.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LimeTime.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap LimeTime {
            get {
                object obj = ResourceManager.GetObject("LimeTime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   [
        ///    {
        ///        &quot;Name&quot;: &quot;Shovel Software Insurance Claim&quot;,
        ///        &quot;UID&quot;: &quot;50010000049535&quot;,
        ///        &quot;TitleID&quot;: &quot;000400000F715C00&quot;,
        ///        &quot;Version&quot;: &quot;N/A&quot;,
        ///        &quot;Size&quot;: &quot;25.7 MB [206 blocks]&quot;,
        ///        &quot;Product Code&quot;: &quot;KTR-N-CF6P&quot;,
        ///        &quot;Publisher&quot;: &quot;Batafurai&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;D.U.N.K.L.E.R&quot;,
        ///        &quot;UID&quot;: &quot;50010000049475&quot;,
        ///        &quot;TitleID&quot;: &quot;000400000F715300&quot;,
        ///        &quot;Version&quot;: &quot;N/A&quot;,
        ///        &quot;Size&quot;: &quot;170.3 MB [1362 blocks]&quot;,
        ///        &quot;Product Code&quot;: &quot;KTR-N-CD9P&quot;,
        ///        &quot;Publisher&quot;: [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string list_GB {
            get {
                return ResourceManager.GetString("list_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///    {
        ///        &quot;Name&quot;: &quot;Update data ver. 1.16 Radio Human RPG Free!(\u66f4\u65b0\u30c7\u30fc\u30bf Ver. 1.16 \u96fb\u6ce2\u4eba\u9593\u306eRPG FREE!)&quot;,
        ///        &quot;UID&quot;: &quot;50010000024935&quot;,
        ///        &quot;TitleID&quot;: &quot;0004000E00125D00&quot;,
        ///        &quot;Version&quot;: &quot;17728&quot;,
        ///        &quot;Size&quot;: &quot;107.59 MB [861 blocks]&quot;,
        ///        &quot;Product Code&quot;: &quot;CTR-U-JF7J&quot;,
        ///        &quot;Publisher&quot;: &quot;\u30b8\u30cb\u30a2\u30b9\u30fb\u30bd\u30ce\u30ea\u30c6\u30a3&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;Update data Ver. 1.2 Beyblade B Bay Logger &amp; Puzzle(\u66f4\u65b0\ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string list_JP {
            get {
                return ResourceManager.GetString("list_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///    {
        ///        &quot;Name&quot;: &quot;Mario Cart 7 Update Data Ver.1.2(\ub9c8\ub9ac\uc624 \uce74\ud2b8 7 \uc5c5\ub370\uc774\ud2b8 \ub370\uc774\ud130 Ver. 1.2)&quot;,
        ///        &quot;UID&quot;: &quot;50010000049755&quot;,
        ///        &quot;TitleID&quot;: &quot;0004000E00030A00&quot;,
        ///        &quot;Version&quot;: &quot;3088&quot;,
        ///        &quot;Size&quot;: &quot;5.22 MB [42 blocks]&quot;,
        ///        &quot;Product Code&quot;: &quot;CTR-U-AMKK&quot;,
        ///        &quot;Publisher&quot;: &quot;Nintendo&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;Super Mario Maker for Nintendo 3DS Update Data VER.1.05(\uc288\ud37c \ub9c8\ub9ac\uc624 \uba54\uc774\ucee4 for \ub2cc\ud150\ub [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string list_KR {
            get {
                return ResourceManager.GetString("list_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///    {
        ///        &quot;Name&quot;: &quot;Update information Ver. 1.2 Mario Racing 7(\u66f4\u65b0\u8cc7\u6599 Ver. 1.2 \u746a\u5229\u6b50\u8cfd\u8eca7)&quot;,
        ///        &quot;UID&quot;: &quot;50010000049756&quot;,
        ///        &quot;TitleID&quot;: &quot;0004000E0008B400&quot;,
        ///        &quot;Version&quot;: &quot;3088&quot;,
        ///        &quot;Size&quot;: &quot;5.22 MB [42 blocks]&quot;,
        ///        &quot;Product Code&quot;: &quot;CTR-U-AMKW&quot;,
        ///        &quot;Publisher&quot;: &quot;Nintendo&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;Update information VER. 1.4.0 Monster Hunter XX(\u66f4\u65b0\u8cc7\u6599 Ver. 1.4.0 MONSTER HUNTER XX)&quot;,
        ///        &quot;UID&quot;: &quot;50010000042617&quot;, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string list_TW {
            get {
                return ResourceManager.GetString("list_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///    {
        ///        &quot;Name&quot;: &quot;Fragrant Story Update Ver. 1.1&quot;,
        ///        &quot;UID&quot;: &quot;50010000049735&quot;,
        ///        &quot;TitleID&quot;: &quot;0004000E001E2B00&quot;,
        ///        &quot;Version&quot;: &quot;1056&quot;,
        ///        &quot;Size&quot;: &quot;594.8 KB [5 blocks]&quot;,
        ///        &quot;Product Code&quot;: &quot;CTR-U-A4AE&quot;,
        ///        &quot;Publisher&quot;: &quot;William Kage&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;Mario Kart\u2122 7 Update Ver. 1.2&quot;,
        ///        &quot;UID&quot;: &quot;50010000010363&quot;,
        ///        &quot;TitleID&quot;: &quot;0004000E00030800&quot;,
        ///        &quot;Version&quot;: &quot;3152&quot;,
        ///        &quot;Size&quot;: &quot;5.22 MB [42 blocks]&quot;,
        ///        &quot;Product Code&quot;: &quot;CTR-U-AMKE&quot;, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string list_US {
            get {
                return ResourceManager.GetString("list_US", resourceCulture);
            }
        }
    }
}
